
describe('Connect four test', () => {
  it('test home page', () => {
    cy.visit('')
    cy.getData('menu-buttom').should('have.length', 3)
    cy.getData('menu-buttom').its(0).should('have.text', 'PLAYER VS CPU')
    cy.getData('menu-buttom').its(1).should('have.text', 'PLAYER VS PLAYER')
    cy.getData('menu-buttom').its(2).should('have.text', 'REGRAS')

    cy.getData('player-button').click()
    cy.location("pathname").should("equal", "/math")

    cy.getData('player-name').should('have.length', 4)

    cy.visit('')
    cy.getData('cpu-button').click()
    cy.location("pathname").should("equal", "/mathcpu")

    cy.getData('player-name').should('have.length', 4)

    cy.visit('')
    cy.getData('rules-button').click()
    cy.location("pathname").should("equal", "/rules")

    cy.getData('rules-title').should('be.visible')
  })
  it('test rules page', ()=>{
    cy.visit('rules')
    cy.contains('Ser o primeiro jogador a conectar quatro discos da mesma cor (na vertical, horizontal ou diagonal)').should('be.visible')
    cy.get('[data-test="rules-check"]').click()
    cy.location('pathname').should('equal', '/')
  })
  it('test match page', ()=> {
    cy.visit('/math')

    // test menu
    cy.get('[data-test="menu-alert"]').should('not.exist')
    cy.get('[data-test="math-menu-button"]').click()
    cy.get('[data-test="menu-alert"]').as('menu-alert').should('be.visible')
    cy.get('[data-test="menu-alert-title"]').should('have.text', 'Tem certeza que deseja voltar para o menu principal?')
    cy.get('[data-test="menu-alert-button"]').click()
    cy.get('@menu-alert').should('not.exist')

    cy.visit('/math')

    //test scores
    cy.get('[data-test="player-container-1"]').as('player-1').within(()=>{
      cy.get('[data-test="player-name"]').as('player-1-name').should('have.text', 'player 1')
      cy.get('[data-test="player-score"]').as('player-1-score').should('have.text', 0)
    })
    cy.get('[data-test="player-container-2"]').as('player-2').within(()=>{
      cy.get('[data-test="player-name"]').as('player-2-name').should('have.text', 'player 2')
      cy.get('[data-test="player-score"]').as('player-2-score').should('have.text', 0)
    })
    
    // test player round
    cy.get('[data-test="player-1-round-icon"]').as('player-1-round-icon').should('be.visible')
    cy.get('[data-test="math-round-player"]').as('math-round-player').should('have.text', 'Jogador 1')
    cy.get('[data-test="hitbox-0"]').as('hitbox-0').click()
    
    cy.get('@player-1-round-icon').should('not.be.visible')
    cy.get('[data-test="player-2-round-icon"]').as('player-2-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 2')

    // test hitbox
    cy.get('@hitbox-0').click()
    cy.get('@player-1-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 1')
    cy.wait(100)
    cy.get('[data-test="hitbox-1"]').as('hitbox-1').click()
    cy.get('@player-2-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 2')
    cy.wait(100)
    cy.get('[data-test="hitbox-2"]').as('hitbox-2').click()
    cy.get('@player-1-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 1')
    cy.wait(100)
    cy.get('[data-test="hitbox-3"]').as('hitbox-3').click()
    cy.get('@player-2-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 2')
    cy.wait(100)
    cy.get('[data-test="hitbox-4"]').as('hitbox-4').click()
    cy.get('@player-1-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 1')
    cy.wait(100)
    cy.get('[data-test="hitbox-5"]').as('hitbox-5').click()
    cy.get('@player-2-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 2')
    cy.wait(100)
    cy.get('[data-test="hitbox-6"]').as('hitbox-6').click()
    cy.get('@player-1-round-icon').should('be.visible')
    cy.get('@math-round-player').should('have.text', 'Jogador 1')

    // test restart button
    cy.get('[data-test="restart-alert-container"]').should('not.exist')
    cy.get('[data-test="math-restart-button"]').click()
    cy.get('[data-test="restart-alert-container"]').should('be.visible')
    cy.get('[data-test="restart-alert-button"]').click()
    cy.get('@player-1-score').should('have.text', 0)
    cy.get('@player-2-score').should('have.text', 0)

    cy.get('[data-test="math-winner-container"]').should('not.exist')

    // test vertical win
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()

    cy.get('[data-test="math-winner-container"]').as('math-winner-container').should('be.visible')
    cy.get('@player-1-score').should('have.text', 1)
    cy.get('[data-test="next-round-button"]').as('next-round-button').click()
    cy.get('@math-winner-container').should('not.exist')

    // horizontal win
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()

    cy.get('@math-winner-container').should('be.visible')
    cy.get('@player-2-score').should('have.text', 1)
    cy.get('@next-round-button').click()
    cy.get('@math-winner-container').should('not.exist')

    //diagonal right win
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()
    cy.wait(100)

    cy.get('@math-winner-container').should('be.visible')
    cy.get('@player-1-score').should('have.text', 2)
    cy.get('@next-round-button').click()
    cy.get('@math-winner-container').should('not.exist')

    //diagonal left win

    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-1').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-2').click()
    cy.wait(100)
    cy.get('@hitbox-0').click()
    cy.wait(100)
    cy.get('@hitbox-3').click()

    cy.get('@math-winner-container').should('be.visible')
    cy.get('@player-1-score').should('have.text', 3)
    cy.get('@next-round-button').click()
    cy.get('@math-winner-container').should('not.exist')

    // test restart button
    cy.get('[data-test="restart-alert-container"]').should('not.exist')
    cy.get('[data-test="math-restart-button"]').click()
    cy.get('[data-test="restart-alert-container"]').should('be.visible')
    cy.get('[data-test="restart-alert-button"]').click()
    cy.get('@player-1-score').should('have.text', 0)
    cy.get('@player-2-score').should('have.text', 0)
  })
})